sudo: required
language: java

services:
    - docker

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce

script:
    - docker build -t narou-analyze-dev -f Dockerfile-dev .
    - docker run -d --name db -e "POSTGRES_PASSWORD=db_pass" -e "POSTGRES_USER=db_user" -e "POSTGRES_DB=narou_analyze" postgres
    - docker run --rm --name narou_analyze -v "${HOME}/.m2:/root/.m2" -v "${PWD}:/var/my-app" --link db:db -e "NAROU_CRAWLER_DB_USER=db_user" -e "NAROU_CRAWLER_DB_PASS=db_pass" -e "NAROU_CRAWLER_DB_HOST=db" -e "NAROU_CRAWLER_DB_NAME=narou_analyze" narou-analyze-dev
    - docker kill db
    - docker build -t u6kapps/narou-analyze .

after_success:
    - if [ -n "$TRAVIS_TAG" ]; then
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
          docker tag u6kapps/narou-analyze u6kapps/narou-analyze:$TRAVIS_TAG;
          docker push u6kapps/narou-analyze;
      else
          echo skip docker push;
      fi
