language: ruby
cache: bundler

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build
  - docker-compose run app

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      docker build -t u6kapps/narou-analyze -f Dockerfile.production .;
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker tag u6kapps/narou-analyze u6kapps/narou-analyze:$TRAVIS_TAG;
      docker push u6kapps/narou-analyze;
    else echo
      skip docker push;
    fi

notifications:
  slack:
    secure: XOEOgKKZsgreDHr1bNGL8I+ixP9rpm4ypp30VrykP97cyFE1+7w/dB0BwbHV1gR/VdarJLOhk0grgzBq/YhMcGbkl4bkm+77iHlArcq9BaLBBuVCCW04QXQxvG3phKsLkH7k6BJDhuHjB0SItGVV/HxHtTNJl6eeke7bDOk/6ip695ZGtRRB2gRlnt/aH75Y0m5Bng/FyNR0HUKSjKYRZmR8FuURo8CohLeP9CtYwqaIWGyyjaTnHyHhI6/VPWtz31kMw1oU9tXmpCOHZRYbu8XhtWCxuF6HBYyBbW388owMQw8EfGTfCPapEPLowcr3T9rnDhIQR8+RzNRPyehg8Ljur2vq+fSr/KYj+nDv5n/jHdT+ekF1f9LPxVIr3Q5F3MDXQPFls6VmlIKCNzxgP3srxOJfR3xpYZLov1Xwma7zH6Dghoej3+A/u9M9cbUeydafM790JUstMpIZQWaKLmkhfG8oCW0gNyMNxzXpd50jcOLSluF6zzYiOmLVVn1QZ5DF5vE5mXSQDwjIadeRDkNmnNIWTMgwyeiMW7EJppy0ZdUkd8CNXP5Y7C4F9fcglNaFJBlaXSNxS42g1CHs/fIftEuK4nTXNHdY1CqH0m50RyPo7wto7fPhORw84eN6hPLKlcJnnnBr3jhCep2PjQ3zTm8Apb0nlfCmCMgO8sw=

