version: '2'

services:
    narou-analyze:
        image: u6kapps/narou-analyze
        environment:
            - "NAROU_CRAWLER_DB_HOST=narou-analyze-db"
            - "NAROU_CRAWLER_DB_USER=${DOCKER_NAROU_ANALYZE_DB_USER}"
            - "NAROU_CRAWLER_DB_PASS=${DOCKER_NAROU_ANALYZE_DB_PASS}"
            - "NAROU_CRAWLER_DB_NAME=${DOCKER_NAROU_ANALYZE_DB_NAME}"
            - "VIRTUAL_HOST=narou-analyze.u6k.me"
            - "VIRTUAL_PORT=8080"
            - "LETSENCRYPT_HOST=narou-analyze.u6k.me"
            - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
        depends_on:
            - narou-analyze-db
        restart: always
    narou-analyze-db:
        image: postgres
        volumes:
            - "${DOCKER_VOLUMES}/narou-analyze/db:/var/lib/postgresql/data"
        environment:
            - "POSTGRES_USER=${DOCKER_NAROU_ANALYZE_DB_USER}"
            - "POSTGRES_PASSWORD=${DOCKER_NAROU_ANALYZE_DB_PASS}"
            - "POSTGRES_DB=${DOCKER_NAROU_ANALYZE_DB_NAME}"
        restart: always

networks:
    default:
        external:
            name: nginxproxy_default
